# Generated by Django 3.1.1 on 2020-09-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('weight', models.BigIntegerField()),
                ('height', models.BigIntegerField()),
                ('age', models.BigIntegerField()),
            ],
        ),
    ]
